library(networkD3)
library(ggplot2)
library(ggpubr)
library(patchwork)
library(gridExtra)
library(png)
library(grid)
library(ggpmisc)
library(plotly)
library(webr)
library(knitr)
library(kableExtra)
library(magrittr)
library(webshot)
library(htmlwidgets)

folder <- dirname(rstudioapi::getSourceEditorContext()$path)

# Read rocket data from csv files.
ft = read.csv(file.path(folder, "table", "falcon table.csv"), row.names = 1, TRUE)
st = read.csv(file.path(folder, "table", "soyuz table.csv"), row.names = 1)
at = read.csv(file.path(folder, "table", "ariane table.csv"), row.names = 1)
stl = read.csv(file.path(folder, "table", "starlink.csv"), row.names = 1)
ow = read.csv(file.path(folder, "table", "oneweb.csv"), row.names = 1)
kp = read.csv(file.path(folder, "table", "kuiper.csv"), row.names = 1)
rct = read.csv(file.path(folder, "table", "rockets_table.csv"), row.names = 1)
ct = read.csv(file.path(folder, "table", "constellationns_table.csv"), row.names = 1)

# Create Tables

path = file.path(folder, 'pics','falcon_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=4.5, height=3, res=480)
print(grid.table(ft))
dev.off()

path = file.path(folder, 'pics','soyuz_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=4.5, height=3, res=480)
print(grid.table(st))
dev.off()

path = file.path(folder, 'pics','ariane_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=4.5, height=3, res=480)
print(grid.table(at))
dev.off()

path = file.path(folder, 'pics','starlink_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=5, height=4, res=480)
print(grid.table(stl))
dev.off()

path = file.path(folder, 'pics','oneweb_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=5, height=4, res=480)
print(grid.table(ow))
dev.off()

path = file.path(folder, 'pics','kuiper_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=5, height=4, res=480)
print(grid.table(kp))
dev.off()

path = file.path(folder, 'pics','rockets_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=12.5, height=3, res=480)
print(grid.table(rct))
dev.off()

path = file.path(folder, 'pics','constellations_table.tiff')
dir.create(file.path(folder, 'pics'),showWarnings = FALSE)
tiff(path, units="in", width=8, height=3, res=480)
print(grid.table(ct))
dev.off()
